//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEXUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class call
    {
        public int call_id { get; set; }
        public string call_code { get; set; }
        public int call_time { get; set; }
        public int user_id { get; set; }
        public int type { get; set; }
    
        public virtual user user { get; set; }
    }
}
