//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEXUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contract
    {
        public int contract_id { get; set; }
        public int status { get; set; }
        public string note { get; set; }
        public int product_id { get; set; }
        public int user_id { get; set; }
        public int employee_id { get; set; }
        public int store_id { get; set; }
        public int signing_date { get; set; }
        public string product_name { get; set; }
        public decimal price { get; set; }
        public int start_date { get; set; }
        public int end_date { get; set; }
        public int product_type { get; set; }
        public int product_time_used { get; set; }
        public Nullable<decimal> ppm_local { get; set; }
        public Nullable<decimal> ppm_std { get; set; }
        public Nullable<decimal> ppm_mobile { get; set; }
        public string address { get; set; }
        public decimal security_deposit { get; set; }
        public int time_used_available { get; set; }
    
        public virtual user user { get; set; }
        public virtual product product { get; set; }
        public virtual store store { get; set; }
        public virtual user user1 { get; set; }
    }
}
