//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEXUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public coupon()
        {
            this.contract = new HashSet<contract>();
        }
    
        public string coupon_code { get; set; }
        public int user_created { get; set; }
        public int user_used { get; set; }
        public int created_date { get; set; }
        public int exprired_date { get; set; }
        public int status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contract> contract { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
