//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEXUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_store
    {
        public int employee_store_id { get; set; }
        public int employee_id { get; set; }
        public int store_id { get; set; }
    
        public virtual user user { get; set; }
        public virtual store store { get; set; }
    }
}
