//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEXUS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NexusDBEntities : DbContext
    {
        public NexusDBEntities()
            : base("name=NexusDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<connection> connection { get; set; }
        public virtual DbSet<connection_group> connection_group { get; set; }
        public virtual DbSet<contract> contract { get; set; }
        public virtual DbSet<coupon> coupon { get; set; }
        public virtual DbSet<employee_store> employee_store { get; set; }
        public virtual DbSet<order> order { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<product_store> product_store { get; set; }
        public virtual DbSet<report> report { get; set; }
        public virtual DbSet<store> store { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_profile> user_profile { get; set; }
    }
}
