//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEXUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int order_id { get; set; }
        public int start_date { get; set; }
        public int end_date { get; set; }
        public int product_id { get; set; }
        public int customer_id { get; set; }
        public string note { get; set; }
        public int employee_id { get; set; }
        public decimal total_price { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual product product { get; set; }
    }
}
