//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEXUS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_profile
    {
        public int user_profile_id { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public Nullable<int> gender { get; set; }
        public string phone_number { get; set; }
        public Nullable<int> birthday { get; set; }
        public string address { get; set; }
        public Nullable<int> created_date { get; set; }
        public Nullable<decimal> money { get; set; }
        public int user_id { get; set; }
    
        public virtual user user { get; set; }
    }
}
